#!/usr/bin/env bash
set -euo pipefail

basedir=$(dirname "$0")/../dependencies
version="${ENVSUBST_VERSION:-v1.4.3}"

src="$1"
dst="$2"

ensure_envsubst () {
  set -eu

  local dir="$1"
  # Version with leading `v`.
  local version="$2"

  local arch
  arch=$(uname -m)
  case $arch in
    aarch64|arm64) arch="arm64";;
    x86_64|amd64) arch="x86_64";;
    *)
      >&2 echo "Unsupported arch: $arch"
      exit 5
    ::
  esac

  local os
  os=$(uname -s)
  if [[ "$os" != "Linux" && "$os" != "Darwin" ]]; then
    >&2 echo "Unsupported os: $os"
    exit 5
  fi

  if [ ! -x "${dir}/envsubst-${version}-${os}-${arch}" ]; then
    download_envsubst "${dir}" "${version}" "${os}" "${arch}"
  else
    >&2 echo "envsubst-${version}-${os}-${arch} already installed"
  fi

  echo "${dir}/envsubst-${version}-${os}-${arch}"
}

download_envsubst () {
  set -eu

  local dir="$1"
  local version="$2"
  local os="$3"
  local arch="$4"

  local url="https://github.com/a8m/envsubst/releases/download/${version}/envsubst-${os}-${arch}"

  >&2 echo "Downloading envsubst-${version}-${os}-${arch} from ${url}"

  curl -fsSLo "${dir}/envsubst-${version}-${os}-${arch}" "${url}"
  chmod +x "${dir}/envsubst-${version}-${os}-${arch}"

  >&2 echo "envsubst-${version}-${os}-${arch} successfully installed"
}

envsubst="$(ensure_envsubst "${basedir}" "${version}")"

mkdir -p "$dst"

find "$src" -type f -name '*.yaml' -print0 |
while IFS= read -r -d '' file; do
    relative="${file#$src/}"
    output="$dst/$relative"

    mkdir -p "$(dirname "$output")"

    "$envsubst" \
        -no-unset \
        -i "$file" \
        -o "$output"
done
