#!/usr/bin/env bash
set -euo pipefail

src="$1"
dst="$2"

mkdir -p "$dst"

find "$src" -type f -name '*.yaml' -print0 |
while IFS= read -r -d '' file; do
    relative="${file#$src/}"
    output="$dst/$relative"

    mkdir -p "$(dirname "$output")"

    envsubst \
        -no-unset \
        -i "$file" \
        -o "$output"
done
